name: deploy on testing

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  checkout_repository:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  setup_environment:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - name: Verify Node.js Installation
          run: node --version
        - name: Install dependencies
          run: |
            cd ReactNodeTesting
            npm install
  build_project:
    runs-on: ubuntu-latest
    steps:
        - name: Build Project
          run: |
            cd ReactNodeTesting
            npm run build-react
  unit_testing:
    runs-on: ubuntu-latest
    steps:
        - name: Unit Testing
          run: |
            cd ReactNodeTesting
            npm run test-react
  lint_code:
    runs-on: ubuntu-latest
    steps:
        - name: Lint Code
          run: |
            cd ReactNodeTesting
            npx eslint src/sum.js src/cartview.js src/shippingOptions.js
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Deploy and Install Dependencies
          if: always()
          id: action-ssh
          uses: tiyee/action-ssh@release
          with:
            host: ${{ secrets.HOST }} 
            port: 18.212.104.42
            username: ubuntu
            privateKey: ${{ secrets.SSH_PEM }} 
            script: |
              cd /home/ubuntu/practice_CICD/ReactNodeTesting
              npm install